export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const AUTH_USER = 'AUTH_USER';
export const PRIVATE = 'PRIVATE';
export const PUBLIC = 'PUBLIC';
export const AUTH_RESTRICTED = 'AUTH_RESTRICTED';
export const LOG_OUT_USER = 'LOG_OUT_USER';
export const GET_PRODUCTS_BY_SALES_ARRIVAL_DATE = 'GET_PRODUCTS_BY_SALES_ARRIVAL_DATE';
export const PRODUCT_SERVER ='/api/products';