export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const AUTH_USER = 'AUTH_USER';
export const PRIVATE = 'PRIVATE';
export const ADMIN_ROUTE = true;
export const PUBLIC = 'PUBLIC';
export const AUTH_RESTRICTED = 'AUTH_RESTRICTED';
export const LOG_OUT_USER = 'LOG_OUT_USER';
export const GET_PRODUCTS_BY_SALES_ARRIVAL_DATE = 'GET_PRODUCTS_BY_SALES_ARRIVAL_DATE';
export const PRODUCT_SERVER ='/api/products';
export const GET_PRODUCT_CATEGORIES = 'GET_PRODUCT_CATEGORIES'
export const GET_PRODUCTS_TO_SHOP = 'GET_PRODUCTS_TO_SHOP'
export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const CLEAR_FORM = 'CLEAR_FORM';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_WOOD = 'ADD_WOOD';